export const JOB_POSITIONS = [
  'Programer',
  'Frontend programer',
  'Backend programer',
  'Full-stack programer',
  'React programer',
  'React Native programer',
  'Java programer',
  'Python programer',
  'iOS programer',
  'Android programer',
  'Softverski inženjer',
  'QA tester',
  'DevOps inženjer',
  'Sistemski administrator',
  'Mrežni administrator',
  'IT podrska',
  'Data analyst',
  'Data scientist',
  'UX/UI dizajner',
  'Grafički dizajner',
  'Product manager',
  'Project manager',
  'Scrum master',
  'Prodavac',
  'Kasir',
  'Komercijalista',
  'Menadžer prodaje',
  'Sales representative',
  'Account manager',
  'Telefonski operater',
  'Korisnička podrška',
  'Marketing menadžer',
  'Digital marketing specijalista',
  'Social media manager',
  'SEO specijalista',
  'Copywriter',
  'Content creator',
  'PR menadžer',
  'Administrativni radnik',
  'Poslovni sekretar',
  'Office manager',
  'HR menadzer',
  'HR specijalista',
  'Regruter',
  'Knjigovođa',
  'Računovođa',
  'Finansijski analitičar',
  'Bankarski službenik',
  'Pravnik',
  'Advokatski pripravnik',
  'Recepcioner',
  'Konobar',
  'Sanker',
  'Kuvar',
  'Pomocni kuvar',
  'Pekar',
  'Poslasticar',
  'Hotelski radnik',
  'Sobarica',
  'Turistički vodič',
  'Magacioner',
  'Viljuškarista',
  'Vozač',
  'Dostavljač',
  'Kurir',
  'Dispečer',
  'Logistički koordinator',
  'Radnik u proizvodnji',
  'Operater u proizvodnji',
  'Kontrolor kvaliteta',
  'Mašinski inženjer',
  'Elektroinženjer',
  'Građevinski inženjer',
  'Arhitekta',
  'Električar',
  'Vodoinstalater',
  'Zavarivač',
  'Bravar',
  'Stolar',
  'Automehaničar',
  'Serviser',
  'Farmaceut',
  'Farmaceutski tehničar',
  'Medicinska sestra',
  'Medicinski tehničar',
  'Negovatelj',
  'Laboratorijski tehničar',
  'Doktor medicine',
  'Stomatolog',
  'Fizioterapeut',
  'Profesor',
  'Nastavnik',
  'Učitelj',
  'Vaspitač',
  'Pedagog',
  'Psiholog',
  'Obezbeđenje',
  'Higijeničar',
  'Frizer',
  'Kozmetičar',
  'Fotograf',
  'Video editor',
] as const;
